<!DOCTYPE html>
<html>
    <?php
    session_start();
    if (!isset($_SESSION['login']) || $_SESSION['login'] === "guest")
        header('Location: ../index.phtml');
    ?>
    
    <head>
        <link rel="stylesheet" type="text/css" href="../css/navigation.css">
        <link rel="stylesheet" type="text/css" href="../css/home.css">
    </head>
    <body>
        <?php
            include("../php/navigation.php");
            navi("home");
            include("../php/home.php");
        ?>
    </body>
</html>